Fix for `Error: Invalid for_each argument` (#13)
* a.permission_set_arn is providing a unique value to the account_assignment name.

However the permission_set_arn can not be determined until after the apply of the permission sets.

Using a.permission_set_arn in account_assignments before the permission sets have been applied will result in the following error.

```
Error: Invalid for_each argument

  on .terraform/modules/sso_account_assignments/modules/account-assignments/main.tf line 30, in resource "aws_ssoadmin_account_assignment" "this":
  30:   for_each = local.assignment_map

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

Attempting to provide a unique (enough) value that is already predetermined before apply by adding a.permission_set_name instead of arn.

Yes, its less unique but there should be only one assignment using the same account, principal, principal type, and permission set name.

Yes, you are carrying 2 values over from the permission set (name and arn) instead of just one (arn). But it gets around the uniqueness problem. I couldnt think of any other good choice at the moment. Maybe someone else will come up with a better value. Maybe use a random_string.name.result?

* Auto Format

* Update modules/account-assignments/variables.tf

Co-authored-by: Johannes Grumböck <johannes.grumboeck@redbull.com>

* Add versions.tf

* Auto Format

* Delete versions.tf

* Auto Format

* Nuru's comment

Co-authored-by: Jason Jorgensen <jjorgensen@ojolabs.com>
Co-authored-by: cloudpossebot <11232728+cloudpossebot@users.noreply.github.com>
Co-authored-by: Andriy Knysh <aknysh@users.noreply.github.com>
Co-authored-by: Johannes Grumböck <johannes.grumboeck@redbull.com>
Co-authored-by: nitrocode <nitrocode@users.noreply.github.com>